# TCL File Generated by Component Editor 13.0sp1
# Mon Feb 17 12:18:31 CET 2025
# DO NOT MODIFY


# 
# nios_system_sqrt_0 "sqrt" v1.0
# Thomas Martin Boulanger Raynaud 2025.02.17.12:18:31
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module nios_system_sqrt_0
# 
set_module_property DESCRIPTION ""
set_module_property NAME nios_system_sqrt_0
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Thomas Martin Boulanger Raynaud"
set_module_property DISPLAY_NAME sqrt
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sqrt
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file nios_system_sqrt_0.vhd VHDL PATH nios_system_sqrt_0.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point nios_system_sqrt_0
# 
add_interface nios_system_sqrt_0 nios_custom_instruction end
set_interface_property nios_system_sqrt_0 clockCycle 0
set_interface_property nios_system_sqrt_0 operands 1
set_interface_property nios_system_sqrt_0 ENABLED true
set_interface_property nios_system_sqrt_0 EXPORT_OF ""
set_interface_property nios_system_sqrt_0 PORT_NAME_MAP ""
set_interface_property nios_system_sqrt_0 SVD_ADDRESS_GROUP ""

add_interface_port nios_system_sqrt_0 clk clk Input 1
add_interface_port nios_system_sqrt_0 reset reset Input 1
add_interface_port nios_system_sqrt_0 clk_en clk_en Input 1
add_interface_port nios_system_sqrt_0 start start Input 1
add_interface_port nios_system_sqrt_0 done done Output 1
add_interface_port nios_system_sqrt_0 dataa dataa Input 32
add_interface_port nios_system_sqrt_0 result result Output 32

